---
driver:
  name: ssh
  ssh_key: spec/test.pem
  username: centos
  sudo: true

provisioner:
  name: ansible_playbook
  roles_path: roles
  ansible_connection: winrm
  private_key: spec/test.pem
  ansible_inventory: inventory/hosts_ssh
  require_windows_support: true
  require_chef_for_busser: false
  kerberos_conf_file: kr.conf
  ansible_host_key_checking: false
  ansible_verbose: true
  ansible_verbosity: 4


platforms:
  - name: centos-7.0

suites:
  - name: ansible
    driver_config:
      hostname: '54.171.221.112'

